server:
  port: 9091
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/free_roc_ship_ali?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
 # resources:
    #static-locations: classpath:/static/,classpath:/views/

  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - classpath:/views/
  application:
    name: generator-roc_ship

runtime:
  datasource: mysql
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql